### PR TITLE
Fix: squid:S2095, Resources should be closed using try-with-resource

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2095 - “Resources should be closed”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2095

Please let me know if you have any questions.
Ayman Elkfrawy.

### CODE REVIEW

**Comment by matzew** [comment]
@elkfrawy-df can you rebase this PR ?

**Comment by elkfrawy-df** [comment]
@matzew Done.

**Comment by matzew** [comment]
@elkfrawy-df looks like TravisCI job is now failing 😕

**Comment by elkfrawy-df** [comment]
@matzew I'm not sure what is the problem, but it seems it faced problem with creating the schema! Maybe you can try running TravisCI again.

**Comment by matzew** [comment]
@elkfrawy-df I did re-trigger it, but same problem. It's not related to Travis, since this once passed:
https://github.com/aerogear/aerogear-unifiedpush-server/pull/740

**Comment by matzew** [comment]
@elkfrawy-df I think that the build failure is related to your changes

**Comment by matzew** [comment]
Closing, since the build is failing - thanks for your contribution, though !

**Pull request closed without merging**
