### PR TITLE
Adding gcm token validation

### PR DESCRIPTION
**Pull request by sinarz**
From gcm docs:

> When you send a notification to a registration id which is expired, for the 1st time the message(notification) will be delivered but you will get a new registration id with the name canonical id. Which mean, the registration id you sent the message to has been changed to this canonical id, so change it on your server side as well.

I submitted a gcm token in aerogear and used it for some time. after that, the token was expired, and it was removed from aerogear database but not removed from database and not replaced with canonical id.
I checked aerogear code and the feature was not implemented in the sender file:
`org.jboss.aerogear.unifiedpush.message.sender.GCMPushNotificationSender.java`

I was wondering if you could add this feature in the cleanupInvalidRegistrationIDsForVariant function of the mentioned file so the gcm tokens that must be replaced wont be removed.

### CODE REVIEW

**Comment by matzew** [comment]
@sinarz thanks for the PR... but, looks like something here went wrong.
I doint see you commit, just 112 other commits.

Can you make sure your commit is correctly rebased off of our master

**Comment by sinarz** [comment]
Hello,
Thanks for your time and fast answer.
Sorry I just know the bug and I just joined github and didn't know I can
commit projects of other people.
So I should make a commit first and then start the pull request?

Regards,
Sina

**Comment by matzew** [comment]
sure, if you have a fix, feel free to push it to your fork/branch and share
via a PR.

We are happy for any contribution - it's open source!

On Tue, Mar 15, 2016 at 1:53 PM, sinarz <notifications@github.com> wrote:

> Hello,
> Thanks for your time and fast answer.
> Sorry I just know the bug and I just joined github and didn't know I can
> commit projects of other people.
> So I should make a commit first and then start the pull request?
>
> Regards,
> Sina
>
> On Tue, Mar 15, 2016 at 4:19 PM, Matthias Wessendorf <
> notifications@github.com> wrote:
>
> > @sinarz <https://github.com/sinarz> thanks for the PR... but, looks like
> > something here went wrong.
> > I doint see you commit, just 112 other commits.
> >
> > Can you make sure your commit is correctly rebased off of our master
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> >
> >
> https://github.com/aerogear/aerogear-unifiedpush-server/pull/690#issuecomment-196803988
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/aerogear/aerogear-unifiedpush-server/pull/690#issuecomment-196805216
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
@sinarz closing this - looks like sent by accident :)

**Pull request closed without merging**
