### PR TITLE
remove views and controllers that are no longer needed AGPUSH-1391

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1391
* removed `views` (dialogs moved from `views/dialogs` to `dialogs`
* removed unused `Controllers` (route-specific controllers now in 
* removed unused directives
* moved endpoints to separated folder (from `services` to `endpoints`)
* few renamings

https://issues.jboss.org/browse/AGPUSH-1387
* made Edit Names in application list and in application detail (variant list) work

https://issues.jboss.org/browse/AGPUSH-1386
* made wizard work
* fixed few typos
* added links to documentation

Testing:

* just click around and make sure there are no errors in the browser console log
* links on the wizard should lead into documentation
* open "secret" page `links-check` to see what links we are missing in documentation: http://localhost:8080/ag-push/#/links-check
  * this page serves as a single page listing all links so that one can check them without navigating through console
  * missing links will be addressed as part of https://issues.jboss.org/browse/AGPUSH-1400

### CODE REVIEW

**Comment by lfryc** [comment]
someone familiar with AngularJS, could you please review this?

**Comment by lfryc** [comment]
I don't believe code review is necessary here as there are just removals and very little of changes. :-)

So we just need to test this a bit.

**Comment by matzew** [comment]
sure thing - will take a :eyes:

**Comment by matzew** [comment]
I am getting "Error! Server returned 404: Not Found", when clicking the send button

**Comment by matzew** [comment]
Create an App, but no variant, than skip the wizard: getting 404 warning note as well

**Comment by matzew** [comment]
clicking on "Delete" for an app, getting the 404 error as well

**Comment by matzew** [comment]
Create an App, in the wizard now click "Add a variant" -> same 404

**Comment by matzew** [comment]
Question: do the (404) errors eventually go away? I have to click the X to make them disappear

**Comment by lfryc** [comment]
Yea, running from a clean env reveals lot of errors. Thanks for testing @matzew , going to fix those..

Error do not disappear without user action, in practice there shouldn't be that much errors, so it make sense :-)

**Comment by lfryc** [comment]
Ah, yea, forgot to test with production build. With `views` moved around and changed paths it would be surprise if it actually worked...

**Comment by lfryc** [comment]
Sometimes even small differences matter, right? Fixed `admin-ui` distribution build..

**Comment by lfryc** [comment]
I will add few more features here..

**Comment by lfryc** [comment]
I've added fixes for these two issues and rebased on master:

[AGPUSH-1387](https://issues.jboss.org/browse/AGPUSH-1387) UPS Console: Edit names of variants and apps is not working
[AGPUSH-1386](https://issues.jboss.org/browse/AGPUSH-1386) UPS Console: leftovers/defficiencies in wizard screens

**Comment by lfryc** [comment]
Ready for testing now..

**Comment by matzew** [comment]
:eyes:

On Thu, May 7, 2015 at 10:07 AM, Lukáš Fryč <notifications@github.com>
wrote:

> Ready for testing now..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/544#issuecomment-99763467>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
Landed on MASTER, thanks @lfryc 

https://github.com/aerogear/aerogear-unifiedpush-server/commit/d0d702525cd998c8245e7badc5064f33acc33560

**Comment by lfryc** [comment]
Thanks @matzew !

**Pull request merged**
