### PR TITLE
Update to KeyCloak 1.2.0.CR1

### PR DESCRIPTION
**Pull request by abstractj**
This updates fixes:

https://issues.jboss.org/browse/AGPUSH-1352

I've already tested against our supported databases, but a sanity check is always welcome.

@sebastienblanc @matzew care to take a look? It depends on https://github.com/aerogear/aerogear-parent/pull/47

### CODE REVIEW

**Comment by matzew** [comment]
:+1: tested fine w/ a fresh installation and new :whale: DB containers

:tada:

**Comment by matzew** [comment]
tested w/ iOS Swift HelloWorld app

**Comment by cvasilak** [comment]
tested using ```wildfly-8.2.0.Final``` with ```PostgreSQL 9.4``` using Android HelloWorld demo and worked great.

:+1:

**Comment by abstractj** [comment]
@matzew @cvasilak landed, thank you!

**Comment by matzew** [comment]
ahm, not sure this should go to master yet :-)

**Pull request closed without merging**
