### PR TITLE
[WIP] WebPush UI

### PR DESCRIPTION
**Pull request by secondsun**
Webpush ui updates.  Needed for testign unifiedpush-admin-ui.

### CODE REVIEW

**Comment by secondsun** [comment]
@ziccardi @wei-lee I'm adding you as reviewers, but we can talk on chat about who should review this and https://github.com/aerogear/unifiedpush-admin-ui/pull/41

**Comment by ziccardi** [comment]
Test fails with: 
```
[INFO] Running org.jboss.aerogear.unifiedpush.migrator.MigratorTest
Exception in thread "mysql" com.mysql.management.util.WrappedException: java.io.IOException: Cannot run program "/Users/ziccardi/work/aerogear/aerogear-unifiedpush-server/migrator/target/unifiedpush/bin/mysqld": error=86, Bad CPU type in executable
	at com.mysql.management.util.Exceptions.toRuntime(Exceptions.java:55)
	at com.mysql.management.util.Exceptions$Block.exec(Exceptions.java:89)
	at com.mysql.management.util.RuntimeI$Default.exec(RuntimeI.java:180)
	at com.mysql.management.util.Shell$Default.run(Shell.java:140)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/Users/ziccardi/work/aerogear/aerogear-unifiedpush-server/migrator/target/unifiedpush/bin/mysqld": error=86, Bad CPU type in executable
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at com.mysql.management.util.RuntimeI$Default$1.inner(RuntimeI.java:177)
	at com.mysql.management.util.Exceptions$Block.exec(Exceptions.java:86)
	... 3 more
Caused by: java.io.IOException: error=86, Bad CPU type in executable
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more
```

**Comment by ziccardi** [comment]
Have not been able to have UPS up and running using `docker-compose` on mac (even after applying https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/docker-compose/README.adoc#solving-bug-in-mac-os-to-use-docker-compose) . On linux it worked very well.

**Comment by secondsun** [comment]
I'm closing this because there will be another update to the ui soon (tm)

**Pull request closed without merging**
