### PR TITLE
Agpush 1611

### PR DESCRIPTION
**Pull request by matzew**
Updating UI to give hints on google pluign for google-service.json

### CODE REVIEW

**Comment by matzew** [comment]
Once https://github.com/aerogear/aerogear-unifiedpush-server/pull/709 is merged, this needs to be updated / rebased

**Comment by matzew** [comment]
@secondsun now that #709  is merged, what's the best code snippet for this ?

**Comment by secondsun** [comment]
@matzew I can create a project without a project # fine, but I cannot remove a project number without triggering a validation error.

**Comment by matzew** [comment]
ok, will fix that tomorrow, on the angular side of the house.

On Wed, May 4, 2016 at 7:43 PM, Hoyt Summers Pittman <
notifications@github.com> wrote:

> @matzew <https://github.com/matzew> I can create a project without a
> project # fine, but I cannot remove a project number without triggering a
> validation error.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/710#issuecomment-216944406>
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by secondsun** [comment]
@matzew see my pr

**Pull request merged**
