### PR TITLE
Details using UPS as a containerized service, which environment varia…

### PR DESCRIPTION
**Pull request by Aindriunannerb**
## Motivation
https://issues.redhat.com/browse/AEROGEAR-10131

## What
This pull request is being done in parts, the first part will detail upgrading to using UPS as a containerized service, the second part will contain information on upgrading UPS to use an operator.

### CODE REVIEW

**Comment by secondsun** [comment]
@Aindriunannerb Can you move the deletions and index updates to a different PR?  I can merge those separately and faster.  (Assuming they aren't needed for your doc)

**Comment by Aindriunannerb** [comment]
> @Aindriunannerb Can you move the deletions and index updates to a different PR? I can merge those separately and faster. (Assuming they aren't needed for your doc)

none of those were needed for this PR, I must have made a mistake with keeping my website branch up to date when creating the AEROGEAR-10131 branch. I performed an interactive rebase and it should be ok now.

**Comment by secondsun** [comment]
@Aindriunannerb I think you might have mixed up the merge, it looks like the whole readme for the operator and the getting started section were appended to the maintenance doc.  Mind running through this in standup friday?

**Comment by ziccardi** [comment]
Moved here: https://github.com/aerogear/aerogear.org/pull/790

**Comment by ziccardi** [comment]
@secondsun Can we merge this?

**Pull request merged**
