### PR TITLE
Updating links, and removing useless, empty links

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc looks good ?

**Comment by lfryc** [comment]
Testing

**Comment by lfryc** [comment]
:+1: works & seems fine, merging...

**Comment by lfryc** [comment]
Landed as https://github.com/aerogear/aerogear-unifiedpush-server/commit/069d95b3ab59d0d5ba1d54a1c498f0f53d94dd7b

**Pull request closed without merging**
