### PR TITLE
Added MireDot as a REST API doc generator

### PR DESCRIPTION
**Pull request by matzew**
Hi @idelpivnitskiy I rebased, got rid of my change and opened a new PR for this.

### CODE REVIEW

**Comment by matzew** [comment]
@idelpivnitskiy intentionally, I left this https://github.com/matzew/aerogear-unifiedpush-server/blob/AGPUSH-1366-miredot/jaxrs/src/main/java/org/jboss/aerogear/unifiedpush/rest/registry/installations/InstallationRegistrationEndpoint.java#L146-L154

;-)

**Comment by idelpivnitskiy** [comment]
@matzew I think that I don't fully understand what should I do now :) Could you clarify?

**Comment by matzew** [comment]
mind applying mirrdot for the new endpoint?

On Friday, May 8, 2015, Idel Pivnitskiy <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> I think that I don't fully understand
> what should I do now :) Could you clarify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/550#issuecomment-100200366>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matzew** [comment]
i will add raw desc. of it

On Friday, May 8, 2015, Matthias Wessendorf <matzew@apache.org> wrote:

> mind applying mirrdot for the new endpoint?
>
> On Friday, May 8, 2015, Idel Pivnitskiy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @matzew <https://github.com/matzew> I think that I don't fully
>> understand what should I do now :) Could you clarify?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/550#issuecomment-100200366>
>> .
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by matzew** [comment]
@idelpivnitskiy ok, my bad, I thought I had some doc here :)

mind transforming that into the miredot format ? 

Also, should we remove the old doclet, now?

**Comment by idelpivnitskiy** [comment]
@matzew I think we should squash current commits and commits from https://github.com/matzew/aerogear-unifiedpush-server/pull/4

**Comment by matzew** [comment]
@idelpivnitskiy rebased and squashed

**Comment by idelpivnitskiy** [comment]
Looks good!
@matzew WDYT about https://github.com/aerogear/aerogear-unifiedpush-server/pull/526#issue-68353713?
> We are also able to:
* change title;
* hide Issues tab;
* add HTML snippet with introduction text.

**Comment by matzew** [comment]
that would be good!

On Monday, May 11, 2015, Idel Pivnitskiy <notifications@github.com> wrote:

> Looks good!
> @matzew <https://github.com/matzew> WDYT about #526 (comment)
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/526#issue-68353713>
> ?
>
> We are also able to:
>
>    - change title;
>    - hide Issues tab;
>    - add HTML snippet with introduction text.
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/550#issuecomment-100861874>
> .
>


-- 
Sent from Gmail Mobile

**Comment by idelpivnitskiy** [comment]
@matzew please, leave a new title and introduction text here, I will add them to MireDot

**Comment by matzew** [comment]
@idelpivnitskiy for which parts? sorry, confused here. for the new metrics endpoint? or all ?

**Comment by idelpivnitskiy** [comment]
@matzew no, I mean a title of HTML-page and a introduction text for all API. See http://www.miredot.com/docs/manual/output-configuration/title/ and http://www.miredot.com/docs/manual/output-configuration/html-intro/

**Comment by sebastienblanc** [comment]
For th title let's use the text from the website `UnifiedPush RESTful Endpoint ${project.version}` , for the intro not sure we need this for now, we can always add it later. 
@idelpivnitskiy Could you also rebase the PR

**Comment by idelpivnitskiy** [comment]
@matzew I will reopen my own PR for this, ok?

**Comment by matzew** [comment]
sure

On Sat, May 23, 2015 at 11:01 PM, Idel Pivnitskiy <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> I will reopen my own PR for this, ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/550#issuecomment-104944267>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by idelpivnitskiy** [comment]
Reopened as #571

**Pull request closed without merging**
