### PR TITLE
AGPUSH-1585 - analytics concurrency issue

### PR DESCRIPTION
**Pull request by matzew**
Introducing a robust message key (variant+pushmessageInfo) to have better message selection from the queues on concurrent requests

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc please review and test

**Comment by matzew** [comment]
@lfryc if you are available - I'd appreciate a look here

**Comment by sebastienblanc** [comment]
:+1:

**Comment by matzew** [comment]
ported to 1.1.x as well -> b7d5dee7c413673d68867e09668940ac97fd6eb5

**Pull request merged**
