### PR TITLE
styles account manager

### PR DESCRIPTION
**Pull request by andresgalante**
@lfryc, can you review this one please? This style step account manager to follow better the console design.

I have this warning when I sent the commit, I don't know what it means:
warning: CRLF will be replaced by LF in admin-ui/app/img/brand.svg.
The file will have its original line endings in your working directory.

### CODE REVIEW

**Comment by lfryc** [comment]
Distribution build didn't show logo ion account management section until applying this fix: https://github.com/andresgalante/aerogear-unifiedpush-server/pull/1/files

**Comment by lfryc** [comment]
The CRLF failure is fine, it just says it decoded line-endings format from one platform to another.

**Comment by andresgalante** [comment]
thanks @lfryc :clap:

**Comment by matzew** [comment]
very cool! :clap:

**Pull request merged**
