### PR TITLE
revamp of UX with all routes and basic functionality AEROGEAR-1335

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1336
https://issues.jboss.org/browse/AGPUSH-1337
https://issues.jboss.org/browse/AGPUSH-1339

* all "routes" (aka page routing) works
* wizard works (up to send notification step)
* adding / removing applications
* adding / removing variants
* :warning: still contains a lot of mockup code
* for non-functional parts, see issues in epic https://issues.jboss.org/browse/AGPUSH-1335

### CODE REVIEW

**Comment by lfryc** [comment]
I will deploy a demo app shortly to show the functionality

**Comment by lfryc** [comment]
@sebastienblanc @abstractj  could you please test locally? :football:

**Comment by lfryc** [comment]
@andresgalante feel free to try it as well, would be nice to have a review if I haven't miss something :-)

**Comment by andresgalante** [comment]
@lfryc great work, routes are good and the things listed are ok :+1:

**Comment by sebastienblanc** [comment]
@lfryc works for me, even with my prevous data :) , except the points you mentioned, I'm +1. What is the next step ? Maybe you can push to a branch on the aerogear org and do the following PR against that ?

**Comment by lfryc** [comment]
@sebastienblanc that's exactly what happened,

thanks for reviews guys!!

**Pull request merged**
