### PR TITLE
Using Skip instead of Cancel

### PR DESCRIPTION
**Pull request by matzew**
@andresgalante @lfryc Most of the screens use Skip, therefore doing the same for these two pages

### CODE REVIEW

**Comment by danielpassos** [comment]
:+1:

**Comment by sebastienblanc** [comment]
+1 merging

**Comment by andresgalante** [comment]
@matzew @sebastienblanc @danielpassos @lfryc "Cancel" on welcome and step1 was correct. The action is "cancel" creating a new app. 
The rest of the steps are skip, because the user would be skipping the wizard.

I recommend going back with the merge.

**Comment by matzew** [comment]
@andresgalante ok - so 'Cancel' on both files (see changed files)

**Comment by andresgalante** [comment]
@matzew yeap, the action is this:
The user clicks on "crate new app"
welcome screen: Gets instructions, he can either cancel or continue
step one: gets the option to name and create the app, again he can either cancel or continue

After this the app has already been crated, so he can no longer cancel it, he can just skip the wizard. Does it make sense?

**Pull request merged**
