### PR TITLE
reintroduced Installation List with search capability AGPUSH-1406

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1406

Summary:
* the device list is conditionally presented to a user in the Variant detail
  * the device list has: search capability
  * ...pagination
  * ability to enable/disable device
* the client device registration snippet is not shown when there are registered devices (but user can click to reveal it by hitting a link)
* and vice versa, no device list is shown when there are "No installations yet" and client device registration snippet is presented then

Note:
* I had to extend REST endpoint by one optional parameter "search" that allows full text search in some comment installation properties

Testing:
* test that features above works as you would expect

A mockup I used as a base for impl: http://andresgalante.com/ups-console/app-detail-variants.html

### CODE REVIEW

**Comment by lfryc** [comment]
@sebastienblanc would you mind to :eyes:  this? :football:

**Comment by sebastienblanc** [comment]
:eyes:

**Comment by matzew** [comment]
+1 tested and works fine

**Comment by matzew** [comment]
@lfryc @sebastienblanc I think this needs a rebase

**Comment by lfryc** [comment]
rebasing

**Comment by lfryc** [comment]
@matzew rebased on latest `master`

**Comment by matzew** [comment]
+1

**Comment by lfryc** [comment]
Once merged, please take a look at https://github.com/aerogear/aerogear-unifiedpush-server/pull/579

**Comment by sebastienblanc** [comment]
Working as expected :) , one remark, there is a text + link just before the table `This is a list of devices using this variable. To see installation instructions and code snippet click here` once on the snippet section there is not really a way to go back to the device list (unless you collapse the variant and open it again), maybe we could add the link to the device list also on the snippet section ?

**Comment by matzew** [comment]
@sebastienblanc is that really needed ? 

@andresgalante any comments?

**Comment by lfryc** [comment]
if you click on "To see installation instructions and code snippet click here"...
the snippets are expanded, but the device list remains still there, it is now under the snippets
is that what you wanted @sebastienblanc ?

**Comment by sebastienblanc** [comment]
Oh Sorry, did not saw it was under the snippets :), then it's all okay :+1

**Comment by lfryc** [comment]
Landed :rocket:

**Pull request merged**
