### PR TITLE
Add installation metrics consumer injection [AGPUSH-2125]

### PR DESCRIPTION
**Pull request by polinankoleva**
Add first Kafka injected consumer in the kafka module.

### CODE REVIEW

**Comment by matzew** [comment]
looks good ! 

let me test it

**Comment by matzew** [comment]
@dimitraz @polinankoleva good to merge ?

**Comment by matzew** [comment]
tests worked fine

**Comment by dimitraz** [comment]
Just testing now

**Comment by dimitraz** [comment]
btw, as a convention, should we always use the prefix `KAFKA_` for topic and group id names? @matzew @polinankoleva

**Comment by matzew** [comment]
> btw, as a convention, should we always use the prefix KAFKA_ for topic and group id names? 

not sure

I thought about moving those names to a common interface, to have them defined in a centralized place.
we could perhaps namespace them with `AGPUSH_xxx` to avoid the names collide w/ other topics, on a larger cluster, used by lot;s of services

**Pull request merged**
