### PR TITLE
Updating token validator for Android and adding new test

### PR DESCRIPTION
**Pull request by matzew**
Done for [AGPUSH-1446](https://issues.jboss.org/browse/AGPUSH-1446)

### CODE REVIEW

**Comment by matzew** [comment]
@danielpassos @sebastienblanc @smiklosovic looks like the Android registrationID now allows colon (:), at least in the emulator.

Please review

**Comment by matzew** [comment]
@danielpassos @sebastienblanc @smiklosovic any comment ?

**Comment by smiklosovic** [comment]
afaik, there is no automated way how to test this from my point of view in integration tests. We are using that proxy thingy and pretending that arrived device token with colon is valid is just useless. If you manage to receive something to real device than I would say it is sufficient to verify it.

**Comment by danielpassos** [comment]
:+1:

**Comment by matzew** [comment]
landed (https://github.com/aerogear/aerogear-unifiedpush-server/commit/b6ee9a462ed033e6faa63aebd3756c1b8f675821)

**Comment by matzew** [comment]
@smiklosovic @danielpassos @sebastienblanc In the GCM 3 presentation from Google IO, I also see a colon (`:`) inside of the registrationID

**Pull request closed without merging**
