### PR TITLE
Change the Keycloak welcome page with HTTP redirect

### PR DESCRIPTION
**Pull request by abstractj**
Good morning, this change refers to AGPUSH-956 and must go on `1.0.x` and on master if makes you happy.

@matzew @lholmquist @kpiwko I would appreciate if you could test it and provide some feedback.

Thanks in advance.

### CODE REVIEW

**Comment by lholmquist** [comment]
after logging in for the first time,  i just get a blank page,   looks like a redirect happens but the url loses the "code" in the query params

**Comment by lholmquist** [comment]
the issue i was having is in Chrome 40,  worked on safari and FF

**Comment by lholmquist** [comment]
Yup,  the rendering in chrome is my issue,   used another chrome browser on a differnt computer and it worked ok, 

So what am i suppose to be clicking on?

**Comment by abstractj** [comment]
@lholmquist damnit Google! Please test with the latest change, I did some tests here with Chrome 40 running Incognito and Firefox, seems like now, it works.

**Comment by matzew** [comment]
:eyes: at it

**Comment by matzew** [comment]
:+1: Works like a charm!

**Comment by kpiwko** [comment]
@okiss can you please check this stuff?

**Comment by okiss** [comment]
It doesn't seem to work for me - when I go to http://localhost:8080/auth/, i get a login form which takes me to UPS, not KeyCloak console.

In UPS, the admin->Account Management link doesn't work as expected. It takes me to UPS dashboard. 

In Chrome 36, the UPS logout link doesn't work either, it also opens the dashboard. It works fine in Firefox 34.

The only way I could enter the KC console was to enter http://localhost:8080/auth/admin/aerogear/console/index.html in the navigation bar.

**Comment by abstractj** [comment]
@okiss I might misunderstood @matzew, but that's expected.

If you enter http://localhost:8080/auth/, you must be redirected to `ag-push`. If people want to access Keycloak console, they must provide the full URL like described at our documentation. Right @matzew?

**Comment by matzew** [comment]
> It doesn't seem to work for me - when I go to http://localhost:8080/auth/, i get a login form which takes me to UPS, not KeyCloak console.

Yes, that _is_ expected - we don't (yet) fully support the Keycloak console yet (note: we are tech preview). Therefore we don't want to expose the link.

Accessing is still possible. The real link is covered on the doc. That's good enough for now

**Comment by matzew** [comment]
@abstractj absolutely right! :-)

**Comment by matzew** [comment]
landed in cd81c894263b96b2571353cfedeeecdbcbb968f4 and e6857ff3cdce205356fbd2a9c49eca1667ffee85

**Comment by matzew** [comment]
Thanks @abstractj :tada:

**Pull request closed without merging**
