### PR TITLE
More scripts

### PR DESCRIPTION
**Pull request by matzew**
Some more scripts that are handy for different environments (e.g. Docker or WF cluster mode)

### CODE REVIEW

**Comment by matzew** [comment]
@danielpassos @sebastienblanc mind to look ?

**Comment by matzew** [comment]
any comment folks ?

**Comment by danielpassos** [comment]
Sorry for the newbie question but where `ups-datasource.yml` will be used?

**Comment by matzew** [comment]
docker - it's in the guide referenced for DBs (and will be dist bundle
download)

On Tue, Jul 7, 2015 at 2:48 PM, Daniel Passos <notifications@github.com>
wrote:

> Sorry for the newbie question but where ups-datasource.yml will be used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/614#issuecomment-119193618>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request merged**
