### PR TITLE
add a nodejs script to test direct grant

### PR DESCRIPTION
**Pull request by sebastienblanc**
@matzew can you take a look ? I did not modify the realm for now but instead I added some instructions in the script. Let's not add a keycloak client just for testing, we can always add it later when it will be really needed.

### CODE REVIEW

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
running `node directgranttest.js`,

and I am getting:
```
receiving data
undefined
receiving data
<html><head><title>JBoss Web/7.5.7.Final-redhat-1 - JBWEB000064: Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>JBWEB000065: HTTP Status 401 - </h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u></u></p><p><b>JBWEB000069: description</b> <u>JBWEB000121: This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>JBoss Web/7.5.7.Final-redhat-1</h3></body></html>
```

**Comment by sebastienblanc** [comment]
Have you created an `ups-client` in kc as mentioned in the script ?

**Comment by matzew** [comment]
landed (w/ little modifications) here: https://github.com/aerogear/aerogear-unifiedpush-server/commit/e83858b9ca8fc2910b44ce8653b2801ef02b3f0d

**Pull request closed without merging**
