### PR TITLE
Removing unused JAX-RS Doclet plugin and profile

### PR DESCRIPTION
**Pull request by matzew**
clean up...

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc @idelpivnitskiy any comments?

**Comment by idelpivnitskiy** [comment]
@matzew great idea :+1: 
But it also would be better to remove Doclet-specific javadoc tags, which are listed here: http://fromage.github.io/jax-doclets/docs/0.10.0/html/#d0e538
Example in our code base: https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/jaxrs/src/main/java/org/jboss/aerogear/unifiedpush/rest/registry/installations/InstallationRegistrationEndpoint.java#L136

**Comment by matzew** [comment]
good point

On Saturday, 9 January 2016, Idel Pivnitskiy <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> great idea [image: :+1:]
> But it also would be better to remove Doclet-specific javadoc tags, which
> are listed here:
> http://fromage.github.io/jax-doclets/docs/0.10.0/html/#d0e538
> Example in our code base:
> https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/jaxrs/src/main/java/org/jboss/aerogear/unifiedpush/rest/registry/installations/InstallationRegistrationEndpoint.java#L136
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/664#issuecomment-170265163>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matzew** [comment]
@idelpivnitskiy mind taking care of this ? I'd really appreciate that,

**Comment by idelpivnitskiy** [comment]
@matzew sure)

**Comment by matzew** [comment]
@idelpivnitskiy the damn javadoc linter is crying like a baby:
```
error: unknown tag: responseheader
[ERROR] * @responseheader deviceCount_variant_{variantID}      Count number of devices for Variant
```
I think, at some point this also needs to be fixed, so we can fully target java-8

**Comment by matzew** [comment]
landed ...

**Comment by idelpivnitskiy** [comment]
@matzew I know how to fix this problem :) wait a minute for a new PR

**Pull request merged**
