### PR TITLE
allow extending of ups-admin-ui to other consoles AGPUSH-1518

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1518

These are the changes required to allow plugging ups-admin-ui into another UI console (and some related fixes).

Fixes also:
* https://issues.jboss.org/browse/AGPUSH-1485
* https://issues.jboss.org/browse/AGPUSH-1533
* https://issues.jboss.org/browse/AGPUSH-1532

Testing:

focus generally on console's UI functionality - links, tabs, snippets,
see commit messages for more details

### CODE REVIEW

**Comment by lfryc** [comment]
Found bugs:

* when I go to Sender API -> open tab Node.js Sender API, user is redirected to the home page
  * the same happens when clicking on Activity log -> toggle message detail (+ icon)
* I believe we should make the difference between WNS and MPNS more apparent in Add Variant dialog (e.g. by adding shortcut at the end of the push network name: WNS/MPNS)
  * Windows - using Windows Push Network Services
  * Windows - using Microsoft Push Notification Service
*

**Comment by lfryc** [comment]
Bugs fixed.

@matzew @danielpassos could you please test this?

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
When starting without any app, we had presented the wizard before. But now it's like this:

**Comment by lfryc** [comment]
nice catch @matzew , I will take a look, I was trying with some apps present, my bad..

**Comment by lfryc** [comment]
after upgrade of angular-router lib, $router.navigate('/welcome') doesn't have desired effect (doesn't navigate to wizard's /welcome screen)

**Comment by lfryc** [comment]
Closing this for now, before I get a fix ready.

**Comment by lfryc** [comment]
Please test that:

* when there are no applications (e.g. you delete last one, you are navigated to the /welcome page)
* app-creation wizard works as expected
* bootstrap page works as expected: http://localhost:8080/ag-push/#/bootstrap

**Comment by lfryc** [comment]
@matzew could you please give this another spin?

**Comment by matzew** [comment]
I did click around a bit, and, well it works :)

**Comment by matzew** [comment]
@lfryc do we need more here, ?

**Comment by lfryc** [comment]
@matzew I don't think so, merging this...

**Pull request merged**
