### PR TITLE
implemented Send Push dialog AGPUSH-1342

### PR DESCRIPTION
**Pull request by lfryc**
* implemented Send Push dialog
* had to add @Produces(TEXT_PLAIN) to the sender endpoint (it was sending `Content-type: application/json` otherwise)?

https://issues.jboss.org/browse/AGPUSH-1342

Test sending notifications via Send Push in application detail page.

--

To be merged to `ux-revamp` branch.

### CODE REVIEW

**Comment by edewit** [comment]
@Produces(TEXT_PLAIN) that is fine, seems that it is responding with text instead of json

**Comment by edewit** [comment]
get the following error on sending though: https://gist.github.com/edewit/d9f4c199d26537bf28cf#file-send-failure

**Comment by edewit** [comment]
:+1:  tested the sending to android works like a charm

**Comment by lfryc** [comment]
Thanks for testing, Erik, merged: https://github.com/aerogear/aerogear-unifiedpush-server/commit/907ad8936c8faf6a9024ac08053fdbf737bdc5aa

**Pull request closed without merging**
