### PR TITLE
UX revamp: re-introduce idleService for auto-logout AGPUSH-1345

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1345

* as with the old console, after 300s of inactivity, dialog is shown that the user will be logged out after 30s

Testing:

* in order to test this without waiting for 300s, modify locally configuration in `app.js`:

````
var appConfig = {
    logDebugEnabled: false,
    idleDuration: 300, // <--- modify this
    idleWarningDuration : 30,
    keepaliveInterval: 5
  };
````

To be merged to `ux-revamp`

### CODE REVIEW

**Comment by lfryc** [comment]
@abstractj would you have time to test this? :football:

**Comment by danielpassos** [comment]
:eyes:

**Comment by abstractj** [comment]
@lfryc sure thing!

**Comment by danielpassos** [comment]
:+1:

**Comment by lfryc** [comment]
Thanks for testing guys, merging...

**Comment by lfryc** [comment]
Merged: https://github.com/aerogear/aerogear-unifiedpush-server/commit/222bcaec9a3a8504e38e09a461cc4745e7470f2b

**Comment by abstractj** [comment]
@lfryc I didn't test it, but with @danielpassos +1 + your judgment, I think you're safe.

**Pull request closed without merging**
