### PR TITLE
Changing impl of AGLogger clazz

### PR DESCRIPTION
**Pull request by matzew**
Done for AGPUSH-1417

### CODE REVIEW

**Comment by matzew** [comment]
@smiklosovic @lfryc wanna review?

**Comment by lfryc** [comment]
yes, will test in a bit

**Comment by lfryc** [comment]
works great :+1:

**Comment by lfryc** [comment]
Merged: https://github.com/aerogear/aerogear-unifiedpush-server/commit/72bf319f8afb46858d70b05d1f113440c4938de6

**Pull request closed without merging**
