### PR TITLE
Bootstrap view

### PR DESCRIPTION
**Pull request by lfryc**
@matzew @sebastienblanc could you please review this and test it? :eyes: 

*testing:*

You can access the bootstrap view on http://localhost:8080/ag-push/#/bootstrap
Once you hit Enable Push, you will be redirected to the app detail and you will see list of variants.

Push Application name is generated and Variant names are copy of their VariantType (android, windows_wns, etc.)

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc awesome stuff, dude!

I wonder if we should actually enable it in 1.2.0 - or even 1.1.1 ? 

PErhaps @andresgalante has some ideas on integrating this view in to the regular UI ?

**Comment by lfryc** [comment]
@andresgalante what do you think? does it fit into the current UI?


@kpiwko this hidden view could be interesting for you guys as well:
http://localhost:8080/ag-push/#/bootstrap

it is a way faster to start with for experienced users than the wizard :-)

**Comment by andresgalante** [comment]
@lfryc @matzew 
I can think on a way to include it, I am just wondering how useful for the user it can be. Do you think we have a use case for a user creating more than one variant at the same time?

**Comment by matzew** [comment]
I guess not now - it's perhaps really more for API based hooks.

LEts keep as is, I guess ... :-)

If we ever have to... we now have a hidden UI :-)

On Wed, Jul 22, 2015 at 4:38 PM, Andres Galante <notifications@github.com>
wrote:

> @lfryc <https://github.com/lfryc> @matzew <https://github.com/matzew>
> I can think on a way to include it, I am just wondering how useful for the
> user it can be. Do you think we have a use case for a user creating more
> than one variant at the same time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/619#issuecomment-123744362>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by kpiwko** [comment]
@lfryc nice!

**Pull request merged**
