### PR TITLE
Adding OR statement

### PR DESCRIPTION
**Pull request by matzew**
MASTER and 1.1.x branch.

Done for https://issues.jboss.org/browse/AGPUSH-1524

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc mind to review/test ?

**Comment by lfryc** [comment]
Sure thing...

**Comment by lfryc** [comment]
:+1: reviewed, tested, looks good

**Comment by matzew** [comment]
1.1.x b78fd938499900264914b007e9f92a84df3b86f1

**Comment by lfryc** [comment]
:+1: yep

**Pull request merged**
