### PR TITLE
using latest parent to get iOS 8 push key from apns release

### PR DESCRIPTION
**Pull request by matzew**
Done for https://issues.jboss.org/browse/AGPUSH-1259

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc can you review? This is the base for https://issues.jboss.org/browse/AGPUSH-1260

**Comment by sebastienblanc** [comment]
@matzew I haven't test the new specific keys since I'm not yet on ios 8.2 but I tested with success the new parent with UPS when you staged it http://lists.jboss.org/pipermail/aerogear-dev/2015-February/010906.html

**Comment by sebastienblanc** [comment]
@corinnekrych could you review ?

**Comment by corinnekrych** [comment]
I'll take a look tomorrow first thing

**Comment by sebastienblanc** [comment]
@corinnekrych @matzew I think we can safely merge this one, because it do not break existing stuff , like mentioned in my first comment. Testing the new keys would happen in the PR for https://issues.jboss.org/browse/AGPUSH-1305 , wdyt ?

**Comment by matzew** [comment]
@sebastienblanc go ahead

**Comment by sebastienblanc** [comment]
:rocket: df867c861ec654e5069d30cc3d88d8bb52556236

**Pull request closed without merging**
