### PR TITLE
UX Revamp: state for Alpha2

### PR DESCRIPTION
**Pull request by lfryc**
Rebased on latest `master`

all: feel free to test this

Part of UX Revamp epic: https://issues.jboss.org/browse/AGPUSH-1229

--

The UI is not in a perfect state, there are still few things to be implemented,
and experience needs to be improved here and there.

The goal of Alpha2 is to deliver main functionality, more features will be added in Betas.

### CODE REVIEW

**Comment by matzew** [comment]
I will take a :eyes:  at it, You will :ear: from me later today

**Comment by andresgalante** [comment]
@lfryc Overall it looks great! I haven't tested the actual sending notifications.
Here are some UX things we should take care for the betas:
https://docs.google.com/a/redhat.com/spreadsheets/d/1tZ9QwRvZGCkCU3EhpNySMB1Bn9Op7XuH_Tj-zh4Mn64/edit?usp=sharing

**Comment by matzew** [comment]
@lfryc in the wizzard, I am not able to send a notification (even I see "registered successfully" on my device log)

@andresgalante @lfryc when creating a variant, it says 0 installations - well :-) I'd be surprised if there are installations, when jumping through the wizzard. I'd say let's remove that

**Comment by matzew** [comment]
On the "send push test", I click the "Send Push Notification and Continue " button, and I am getting to 

```
Congratulations! you have created an app
```

However, the right hand side has a green check for  "Backend: Set up sender API" - but I did not see that in the wizzard

**Comment by matzew** [comment]
@lfryc IMO it would be nice to get the `"Backend: Set up sender API` screen into the wizzard, as well as being able to send a push message from the wizzard.

the sense for "0 installations" (or n installations) on the wizard can be discussed at a later point, ok ?

**Comment by matzew** [comment]
When I delete apps on the overview screen, the `General Statistics` section is not updated

**Comment by matzew** [comment]
besides that, I really love what I see! Great work @lfryc and @andresgalante :fireworks: :tada:

**Comment by lfryc** [comment]
I have addressed concerns around wizard and updating app counter.

**Comment by matzew** [comment]
@lfryc awesome!

One more thing: The "Backend: Set up sender API", should it also show the node.js code ? I agree that cURL does not make sense here, but node would make sense.


BTW. do you want to squash these commits ?

**Comment by lfryc** [comment]
Yes, once we agreed on the release-ready state of UI, I can squash all commits.

**Comment by lfryc** [comment]
@matzew The Sender tabs were updated, reused between screens. I exposed even REST API (with CURL) in both screens..

**Comment by matzew** [comment]
+1

On Friday, April 24, 2015, Lukáš Fryč <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> The Sender tabs were updated, reused
> between screens. I exposed even REST API (with CURL) in both screens..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/537#issuecomment-95873694>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matzew** [comment]
I am fine w/ this and imo lets squash it

tag for alpha2 will come Monday

On Friday, April 24, 2015, Matthias Wessendorf <matzew@apache.org> wrote:

> +1
>
> On Friday, April 24, 2015, Lukáš Fryč <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @matzew <https://github.com/matzew> The Sender tabs were updated, reused
>> between screens. I exposed even REST API (with CURL) in both screens..
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/537#issuecomment-95873694>
>> .
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by lfryc** [comment]
On it...

**Comment by lfryc** [comment]
@matzew squashed, really for a merge

**Comment by matzew** [comment]
+1

@cvasilak mind to do a quick review and merge it?

Thanks,
Matthias

On Friday, April 24, 2015, Lukáš Fryč <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> squashed, really for a merge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/537#issuecomment-95887269>
> .
>


-- 
Sent from Gmail Mobile

**Comment by cvasilak** [comment]
tested fresh and successfully send notifications with Android / iOS :+1: 

Screenshot

**Comment by cvasilak** [comment]
:rocket: landed on https://github.com/aerogear/aerogear-unifiedpush-server/commit/21516088202883cc44f74017d6afffcdac3b1472

**Comment by lfryc** [comment]
Thanks @cvasilak !!

**Pull request merged**
