### PR TITLE
AGPUSH-1413: clustering of ApnsServiceHolder

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1413

ApnsServiceHolder refactored according to https://docs.google.com/drawings/d/1Dt-ANkv7Z0PuyVjdkPrkH0ZAO8VOr8GbZ0dGmL5iXTw/edit?usp=sharing

* register few iOS devices (mock device tokens via REST?)
* configure small batches sizes (so that TokenLoader split tokens to lot of batches)
* start cluster as described in README
* see if both containers receive some tokens for processing and they process them (they don't have to, but they could :-)

### CODE REVIEW

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
I am getting test failures and stack traces :-) (at least on Mac)

**Comment by matzew** [comment]
@sebastienblanc you are on Linux, right ? Can you try the build  ?

**Comment by matzew** [comment]
seems to be a mac issues (since the Linux based Travis CI is happy)

**Comment by sebastienblanc** [comment]
I have also tests failing : 
```
  TestMessageRedelivery.testMessageCannotBeRedelivered:130 all messages must fail to be delivered (remains 10)
  TestMessageRedelivery.testMessageWillBeRedelivered:104 3 tries must time out on resource establishing (remains 3)

```
And also a lot of stacktraces

**Comment by matzew** [comment]
@lfryc closing for now, basically to avoid merges by accident

**Pull request closed without merging**
