### PR TITLE
Updating CURL / Java Senders

### PR DESCRIPTION
**Pull request by matzew**
@lfryc @lholmquist please review. If needed, send a Node.js PR against this branch ;-)

### CODE REVIEW

**Comment by lholmquist** [comment]
@matzew sent one, https://github.com/aerogear/aerogear-unifiedpush-server/pull/551


and +1 for this

**Comment by lfryc** [comment]
:eyes:

**Comment by lfryc** [comment]
Java sender works perfectly, but when I copy&pasted curl command, it can't be either executed in the shell as it is or copied into shell script and get executed.

I believe we should add back slashes `\` at the end of each line for curl command, shouldn't we?

**Comment by matzew** [comment]
@lfryc rebased and besides shrinking to a usful minimum, I have added the backslashes

**Comment by lfryc** [comment]
:+1: @matzew yep, all senders works perfectly now!

merging...

**Pull request merged**
