### PR TITLE
bulk of Admin UI/UX issues AGPUSH-1423

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1423

Hey @andresgalante , could you please test this?

It does not solve all the issues from the linked bulk, but most of them. :-)

### CODE REVIEW

**Comment by lfryc** [comment]
Do not merge yet, closing

**Comment by lfryc** [comment]
Ok, ready for merging now

**Comment by lfryc** [comment]
@sebastienblanc would you mind to test this?

**Comment by matzew** [comment]
thanks, landed!

**Pull request closed without merging**
