### PR TITLE
UX revamp: statistics and counters - AGPUSH-1341

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1341
https://issues.jboss.org/browse/AGPUSH-1343
https://issues.jboss.org/browse/AGPUSH-1371

* home screen
  * implemented General Statistics sidebar
  * added device/message counters
* app detail screen
  * implemented App Statistics sidebar

To be merged to `ux-revamp` branch.

### CODE REVIEW

**Comment by lfryc** [comment]
@lholmquist @andresgalante could you test this PR, guys?

For testing, I would play with adding apps, variants and devices and test that the information is appropriately reflected in statistics / counters ( no page refresh after action should be required, screens auto-update ).

**Comment by lfryc** [comment]
Happy :birthday: @lholmquist

**Comment by lholmquist** [comment]
@lfryc starting to take a look,  it built, so that is a start :)

**Comment by lfryc** [comment]
@lholmquist did you have a chance to test this? If not, don't worry, I can merge to `ux-revamp` branch and we can test it once we will be merging `ux-revamp` to `master` later today.

**Comment by lfryc** [comment]
Merging...

**Comment by lfryc** [comment]
Merged: https://github.com/aerogear/aerogear-unifiedpush-server/commit/447ad4f0ea0ea4867aacfb563f957b1a4ac946a9

**Pull request closed without merging**
