### PR TITLE
[AGPUSH-2096][CHANGE] update docker-compose version file

### PR DESCRIPTION
**Pull request by diogoalbuquerque**
- change version file from 1 to 3.2
- add .env file
- interpolate env vars

### CODE REVIEW

**Comment by matzew** [comment]
@diogoalbuquerque Whoooho! :tada: 

thanks for this PR! 

@secondsun @dimitraz  you guys mind taking a look here too ?

**Comment by matzew** [comment]
@diogoalbuquerque howdy!

I currently have to stay on a bit older version of the docker-engine, I have this:
```
docker-compose version 
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

However, I like your file ;-) how about you do the following changes:
* keep the existing and name to something like `docker-compose-v1.yaml`
* add your file and name it like `docker-compose-v3x.yaml`

How do you feel about this? 

Again, thanks for your work on this!

**Comment by matzew** [comment]
@diogoalbuquerque thanks a lot, dude!

**Comment by dimitraz** [comment]
It looks great! We could probably add health checks / resource constraints etc to make it more similar to @secondsun's template but I don't think that's too necessary for now.. Simple is better!

**Pull request merged**
