### PR TITLE
Configure max days for PushInfo metadataUsing system property to receive max days value to keep PushInfo obje…

### PR DESCRIPTION
**Pull request by matzew**
Done for AGPUSH-1565

* introducing `common` module, for better code share (eventually we will add more code to that)
* using System property for the value of the storeage max days value (will need to be added to aerogear.org, once the 1.2.0 release is out)

### CODE REVIEW

**Comment by sebastienblanc** [comment]
I'm getting
`[ERROR] /home/sebastienblanc/aerogear/ups/aerogear-unifiedpush-server/service/src/test/java/org/jboss/aerogear/unifiedpush/service/PushMessageMetricServiceTest.java:[77,52] error: cannot find symbol
`

**Comment by matzew** [comment]
ah! 😜😝

On Wednesday, 17 February 2016, Sebastien Blanc <notifications@github.com>
wrote:

> I'm getting
> [ERROR]
> /home/sebastienblanc/aerogear/ups/aerogear-unifiedpush-server/service/src/test/java/org/jboss/aerogear/unifiedpush/service/PushMessageMetricServiceTest.java:[77,52]
> error: cannot find symbol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/670#issuecomment-185176713>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matzew** [comment]
@sebastienblanc I have updated this PR - was a minor typo on the system property :-(

**Comment by sebastienblanc** [comment]
:+1: 
Yep All good now

**Pull request merged**
