### PR TITLE
adding bower components to the ignore

### PR DESCRIPTION
**Pull request by matzew**
Looks like left over from https://github.com/aerogear/aerogear-unifiedpush-server/pull/648

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc @lholmquist is this OK ?

**Comment by lfryc** [comment]
@matzew interesting, I would guess it should be ignored by the `.gitignore` specified in `admin-ui` subfolder: https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/admin-ui/.gitignore#L6

**Comment by matzew** [comment]
ok - will update, @lfryc 

btw. same build failure

**Comment by matzew** [comment]
see https://github.com/aerogear/aerogear-unifiedpush-server/pull/655

**Pull request closed without merging**
