### PR TITLE
AGPUSH-1369: UX revamp - finish Variants tab

### PR DESCRIPTION
**Pull request by lfryc**
* added extensions to REST endpoints that allows to collect metrics during push application details retrieval
* added missing edit network details action

Change were made just to `Variants` tab in app detail.

To be merged to `ux-revamp` branch.

### CODE REVIEW

**Comment by lfryc** [comment]
@sebastienblanc @edewit guys, would you have time to review this and merge to `ux-revamp` branch eventually?

**Comment by lfryc** [comment]
@andresgalante feel free to test this as well

**Comment by edewit** [comment]
:eyes:

**Comment by edewit** [comment]
:+1:

**Comment by lfryc** [comment]
Thanks for testing!

Landed: https://github.com/aerogear/aerogear-unifiedpush-server/commit/48c029029c74e7be99315d7bd97d398e26d0dad9

**Pull request closed without merging**
