### PR TITLE
Adding docker compose file for AG-DEV and reference in README

### PR DESCRIPTION
**Pull request by matzew**
Test:

cd into the `docker-compose` folder and run:
```
docker-compose up -d
```

Afterwards access https://$DOCKER_IP:8443/ag-push

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc @danbev @abstractj mind taking a look ?

**Comment by danbev** [comment]
:+1:

**Comment by lfryc** [comment]
:eyes: now, just takes ages to download the docker base images..

**Comment by matzew** [comment]
@lfryc your are connected via 56/k :computer:  ?

**Comment by lfryc** [comment]
nope, I'm using smoke signals..

**Comment by lfryc** [comment]
Ok, runs fine.

:ship: it :exclamation:

**Comment by lfryc** [comment]
Merging...

**Pull request merged**
