### PR TITLE
Deleting embedded UI, using JAR from maven central instead

### PR DESCRIPTION
**Pull request by matzew**
Removing Admin-UI.

We use JAR build (latest release) of this one:
https://github.com/aerogear/unifiedpush-admin-ui

### CODE REVIEW

**Comment by matzew** [comment]
@lholmquist yay ? :-)

**Comment by lholmquist** [comment]
@matzew go for it :)

i was thinking you would publish the admin ui to the npm registry,  but since the main project is mvn based, this probably makes sense since you wouldn't need maven to call npm

**Comment by matzew** [comment]
@lholmquist well, we build the UI via NPM, and bundle that in a JAR. but htat's all done on the UI itself.

Here, we just put in the JAR dependency, which is IMO much easier instead of any npm related fu - I am open for suggestions, though

**Comment by yanivmn** [comment]
Extracting jar without JDK is difficult. how about publishing tar.gz to maven central?
i can publish this PR to https://github.com/aerogear/unifiedpush-admin-ui if you like?

**Comment by lholmquist** [comment]
@matzew yea,  that looks easier.   👍

**Comment by matzew** [comment]
@lholmquist yep, sure

**Comment by matzew** [comment]
@yanivmn yeah, please do that - really appreciated

**Comment by yanivmn** [comment]
Done, cheers.

**Pull request merged**
