### PR TITLE
Use httpcomponent properties declared in AeroGear BOM (no overrides)

### PR DESCRIPTION
**Pull request by vibe13**
To be merged after https://github.com/aerogear/aerogear-parent/pull/52

### CODE REVIEW

**Comment by matzew** [comment]
will there be no code change required?

**Comment by lfryc** [comment]
as long as the build passes I guess we are good to go

**Comment by vibe13** [comment]
@matzew @lfryc yes exactly, this PR uses the same versions currently in use, but instead of declaring unused versions in aerogear-parent and overriding them in UPS, it changes the versions in aerogear-parent with the ones currently used, and gets rid of the override in UPS.

**Comment by matzew** [comment]
@lfryc @vibe13 should we include this in 1.1.0 final too ?

**Comment by vibe13** [comment]
@matzew hi Matt this is more a nice to have, but not essential for the release. It would require a new release of aerogear-parent also (after https://github.com/aerogear/aerogear-parent/pull/52 merge), and the inclusion if this new parent

**Comment by matzew** [comment]
ok, thanks - I missed that cross reference. not merging :)

**Pull request closed without merging**
