### PR TITLE
UX revamp: activity log AGPUSH-1340

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1340

This PR contains:

* basic implementation of activity log tab with pagination
* the search does not work yet

In order to test it:

* register app and variant and push a message (it should succeed with message sent to 0 installations)
* register device (either fake or real) and push message (it should either fail or succeed)

To be merged to `ux-revamp` branch.

### CODE REVIEW

**Comment by lfryc** [comment]
@cvasilak could you please test this?

**Comment by cvasilak** [comment]
:eyes: on it

**Comment by cvasilak** [comment]
testing:
>  register app and variant and push a message (it should succeed with message sent to 0 installations) 

- registered a variant (Android) and succeeded. Other variants couldn't be registered(e.g iOS), gaving me an error (```415 Unsupported Media Type```) on the console. Not sure if its because of WIP nature of this branch
- On the Activity log, noticed if it is the current active tab, and send a message, the log table is not refreshed. Need to click on some other tab and click again on the Activity tab to see the table updated.
That said, pagination worked correctly after sending multitude of messages

> register device (either fake or real) and push message (it should either fail or succeed)

Used HelloWorld Android demo, registered successfully and messages pass through

screenshot

**Comment by lfryc** [comment]
Thanks for feedback @cvasilak , I'll look into these problems closely

**Comment by lfryc** [comment]
@cvasilak should be fixed now, could you take it for another test-drive?

**Comment by cvasilak** [comment]
@lfryc I can now successfully register all variants apart from iOS in which I get back an err ```400 - Bad Request```

Screenshot

**Comment by cvasilak** [comment]
@lfryc yay!  :+1: 

Screenshot

**Comment by lfryc** [comment]
Merging...

**Comment by lfryc** [comment]
Merged: https://github.com/aerogear/aerogear-unifiedpush-server/commit/e26ab784fa5661c9def786d914ec7e9f67a17eab

**Pull request closed without merging**
