### PR TITLE
Revert "Updating JPSInstallationDao to use variant.id instead of vari…

### PR DESCRIPTION
**Pull request by danbev**
…antID"

This reverts commit 75ff5cdad7ca1561ab62ccd5ac3bf0a0b0826c5d.

### CODE REVIEW

**Comment by danbev** [comment]
@sebastienblanc @matzew Can you give try this out and review? 
I can see that installations are now found but I was not able to send a push notification to my iOS device. This currently fails with the following error: 
```
12:00:55,215 INFO  [com.notnoop.apns.internal.ApnsConnectionImpl] (Thread-38 (HornetQ-client-global-threads-1003304940)) Failed to send message Message(Id=1; Token=513C6AF82CA0763AE6D5C07626E0DFF367394BCD1C1F135734F4BEA1873A292C; Payload={"aerogear-push-id":"647c9fdf-f26e-4514-a56c-6a844d051b56","aps":{"badge":-1,"alert":{"action":null,"body":"afad","title":null,"title-loc-key":null},"sound":"default","url-args":null}})... trying again after delay: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189) [rt.jar:1.8.0_31]
	at java.net.SocketInputStream.read(SocketInputStream.java:121) [rt.jar:1.8.0_31]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) [jsse.jar:1.8.0_31]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) [jsse.jar:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961) [jsse.jar:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363) [jsse.jar:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:735) [jsse.jar:1.8.0_31]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) [jsse.jar:1.8.0_31]
	at java.io.OutputStream.write(OutputStream.java:75) [rt.jar:1.8.0_31]
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:328) [apns-1.0.0.Beta6.jar:]
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:312) [apns-1.0.0.Beta6.jar:]
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46) [apns-1.0.0.Beta6.jar:]
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:102) [apns-1.0.0.Beta6.jar:]
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36) [apns-1.0.0.Beta6.jar:]
	at org.jboss.aerogear.unifiedpush.message.sender.APNsPushNotificationSender.sendPushMessage(APNsPushNotificationSender.java:164) [unifiedpush-push-sender-1.1.0.Final-SNAPSHOT.jar:1.1.0.Final-SNAPSHOT]
	at org.jboss.aerogear.unifiedpush.message.NotificationDispatcher.sendMessagesToPushNetwork(NotificationDispatcher.java:73) [unifiedpush-push-sender-1.1.0.Final-SNAPSHOT.jar:1.1.0.Final-SNAPSHOT]
```
Could one of you please try with an iOS variant to see if this works for you and if this is an issue with the network I'm on perhaps.

**Comment by matzew** [comment]
@danbev I can take a look this night, or tomorrow morning as my first

@sebastienblanc you have any iOS device in the meantime ?

**Comment by sebastienblanc** [comment]
@danbev I think you can open a separate issue for the iOS problem

**Comment by danbev** [comment]
@sebastienblanc Done, created https://issues.jboss.org/browse/AGPUSH-1497

**Comment by sebastienblanc** [comment]
:+1: 
@edewit Could you also take a look  ? And looks like this revert also fixes AGPUSH-1492

**Comment by matzew** [comment]
I can not reproduce the failure, using a development certificate

**Comment by danbev** [comment]
@matzew Let me double check my environment including my certificates like @sebastienblanc suggested. Sounds like this is an error on my part. Thanks for testing.

**Comment by danbev** [comment]
@sebastienblanc @matzew Sorry guys, it was indeed my certificate that had expired. I thought I checked this yesterday but obviously did not. Please ignore the error I reported and sorry about wasting you time.

**Comment by edewit** [comment]
:+1: solves both issues

**Pull request merged**
