### PR TITLE
AGPUSH-1276 : made reason a lob

### PR DESCRIPTION
**Pull request by sebastienblanc**
@edewit @lfryc : Could you test ? We should make sure that also works for h2 and postgresql

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc can you make sure this is covered in the migrations of @qmx ?

**Comment by sebastienblanc** [comment]
@matzew I already created https://issues.jboss.org/browse/AGPUSH-1291 and assigned to @qmx  to track this ;)

**Comment by lfryc** [comment]
@sebastienblanc could you please describe how can one test this? I understand what happens but reproducing steps would be handy!

**Comment by lfryc** [comment]
Could we possibly write an automated test (Arquillian?) for such a case?

**Comment by sebastienblanc** [comment]
@lfryc To repdoduce this, create a WNS variant, register at least one device (or fake it with a curl) than run this cURL that should produce an error response from the Windows Servers : https://gist.github.com/edewit/b40b8a8e53886976ee67

**Comment by matzew** [comment]
@sebastienblanc what's the status here ?

**Comment by qmx** [comment]
I think @sebastienblanc is waiting for the migration PR to land

**Comment by sebastienblanc** [comment]
@qmx this is for master only so not really related to the current migration bits. But it will be for migration 1.0.3 > 1.1 ;) 
@matzew I'm waiting for @lfryc to test this but tbh the prio is not super high on this, we could wait for the Beta1 ?

**Comment by matzew** [comment]
let's NOT yet focus ont he 1.0.3 migration to 1.1.x.
We really need to take care of 1.0.0 and 1.0.2. that's all

On Fri, Mar 6, 2015 at 10:13 AM, Sebastien Blanc <notifications@github.com>
wrote:

> @qmx <https://github.com/qmx> this is for master only so not really
> related to the current migration bits. But it will be for migration 1.0.3 >
> 1.1 ;)
> @matzew <https://github.com/matzew> I'm waiting for @lfryc
> <https://github.com/lfryc> to test this but tbh the prio is not super
> high on this, we could wait for the Beta1 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/501#issuecomment-77528217>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
@sebastienblanc can this be merged? or is that required to go 'live' after the migration PR ?

**Comment by qmx** [comment]
@matzew I'd advise against adding another **lob** - as you have seen with the ios certificate, those can become a pain to deal with regart to portability between databases

**Comment by matzew** [comment]
ok, sounds good

On Mon, Mar 9, 2015 at 3:57 PM, Douglas Campos <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> I'd advise against adding another
> *lob* - as you have seen with the ios certificate, those can become a
> pain to deal with regart to portability between databases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/501#issuecomment-77868734>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
@sebastienblanc @qmx how about just increasing the column, like https://github.com/sebastienblanc/aerogear-unified-push-server/blob/AGPUSH-1276/model/jpa/src/main/resources/META-INF/orm.xml#L44 ? (perhaps not that long?)

**Comment by sebastienblanc** [comment]
Let me make some additional tests but I remmeber going to @lob because even
increasing to 4096 was not enough (Error message from Microsoft's Server
can be really long since it include the payload you sent).

**Comment by matzew** [comment]
Aren't we just storing the exception? with a little bit of background? I am
not sure it helps to return/store a complete webpage, containing some error

On Mon, Mar 9, 2015 at 6:09 PM, Sebastien Blanc <notifications@github.com>
wrote:

> Let me make some additional tests but I remmeber going to @lob because even
> increasing to 4096 was not enough (Error message from Microsoft's Server
> can be really long since it include the payload you sent).
>
>
> On Mon, Mar 9, 2015 at 5:04 PM, Matthias Wessendorf <
> notifications@github.com> wrote:
>
> > @sebastienblanc <https://github.com/sebastienblanc> @qmx
> > <https://github.com/qmx> how about just increasing the column, like
> >
> https://github.com/sebastienblanc/aerogear-unified-push-server/blob/AGPUSH-1276/model/jpa/src/main/resources/META-INF/orm.xml#L44
> > ? (perhaps not that long?)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/aerogear/aerogear-unifiedpush-server/pull/501#issuecomment-77883247
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/501#issuecomment-77897290>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by sebastienblanc** [comment]
It's not a complete webpage ;) and actually the error message is really meanful and helps. It's really something that would help me and would like to see  on the dashboard. Maybe we can strip it but it feels a bit hacky/messy.

**Comment by matzew** [comment]
@sebastienblanc any example of the MS error? I just find our stack-trace on the JIRA, but not the actual MS error that causes it

**Comment by sebastienblanc** [comment]
@matzew For instance : 
```
this template needs 6 fields, but you specified 14 : [https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, https://avatars2.githubusercontent.com/u/335133?s=140, HELLO!, foreground text, foreground text, foreground text, foreground text, foreground text]
```
So yeah, it's not that long but I remember I struggled to find the right annotation that would both work with h2/mySql/postgresql and @lob seems to the one ... I can close this PR and find a better solution ...

**Comment by matzew** [comment]
@sebastienblanc that seems best, closing for now

**Pull request closed without merging**
