### PR TITLE
UX: Blank slates

### PR DESCRIPTION
**Pull request by lfryc**
On Activity / Analytics we will show just a blank slate if no push notifications were sent.

### CODE REVIEW

**Comment by lfryc** [comment]
Let me criticize my own work a bit in order to find a solution:

* let's create an empty app and add one variant (do not register a device)
* switch to Activity tab
* Push a notification
* perfect, now we solved what the blank slate told us, but we still see "0 Push Notifications" and no charts
  * we can't show charts since there were no devices we could sent notification to

Push Notification in fact show number of Receivers.

What should we show then?

* Number of receivers?
* Number of Push Messages Sent? (even when they were not delivered to any device?)

Should we should Activity without charts when there are no receivers? Two options:

* fix the blank slate to show additional instructions ("register a device and then push notification")
* should the analytics page even though there are no charts

**Comment by lfryc** [comment]
As agreed on IRC, we will just add Push Notifications box into Analytics view, which solves both problems.

**Comment by lfryc** [comment]
@andresgalante as discussed on IRC, we still may want to add this "mini-blank" slate that would guide user to register a device.

**Comment by lfryc** [comment]
latest version + rebased, should be perfect now :-)

@sebastienblanc mind to review this?

@andresgalante you too?

**Comment by lfryc** [comment]
@sebastienblanc would you mind to take a look?

Activity / Analytics tabs now changes according to the number of registered devices / sent push notifications.

**Comment by sebastienblanc** [comment]
:eyes:

**Comment by sebastienblanc** [comment]
I'm a bit confused by the naming "push receivers" , in my tests it shows 2 but I have only 1 devices registered. So I understand it means "the number of notifications that has reached a devices" but I think we should find a better name : 
stats

**Comment by andresgalante** [comment]
@lfryc @sebastienblanc is right. What about changing if we change it "message delivered" and "messages sent" instead o "push notification"

what do you guys think?

**Comment by edewit** [comment]
How do we know the is received? Doesn't the current implementation only send back a response when the app was opened with the message.

**Comment by matzew** [comment]
yes, @edewit is right. Received is not what we track.
The message can sit long (e.g. 5 days) on the phone (received:true), but
the user was just not opening the phone. Now on day 6 he opens the app w/
that push means not it was received at this moment

On Wed, Jun 3, 2015 at 1:01 PM, Erik Jan de Wit <notifications@github.com>
wrote:

> How do we know the is received? Doesn't the current implementation only
> send back a response when the app was opened with the message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/580#issuecomment-108298414>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
Wondering why the confusion is back at "received" vs. "open" etc :-/

On Wed, Jun 3, 2015 at 1:03 PM, Matthias Wessendorf <matzew@apache.org>
wrote:

> yes, @edewit is right. Received is not what we track.
> The message can sit long (e.g. 5 days) on the phone (received:true), but
> the user was just not opening the phone. Now on day 6 he opens the app w/
> that push means not it was received at this moment
>
> On Wed, Jun 3, 2015 at 1:01 PM, Erik Jan de Wit <notifications@github.com>
> wrote:
>
>> How do we know the is received? Doesn't the current implementation only
>> send back a response when the app was opened with the message.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/580#issuecomment-108298414>
>> .
>>
>
>
>
> --
> Matthias Wessendorf
>
> blog: http://matthiaswessendorf.wordpress.com/
> sessions: http://www.slideshare.net/mwessendorf
> twitter: http://twitter.com/mwessendorf
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by sebastienblanc** [comment]
Just a naming confusion, @edewit is indeed right but that is the idea, we could say "targeted receivers"

**Comment by lfryc** [comment]
What about Messaged Dispatched / Messages Open?

**Comment by matzew** [comment]
hrm, better than received :-)

On Wed, Jun 3, 2015 at 3:44 PM, Lukáš Fryč <notifications@github.com> wrote:

> What about Messaged Dispatched / Messages Open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/580#issuecomment-108421860>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by lfryc** [comment]
We need to rename it in the Statistics sidebar then, "2 Notifications" to be consistent.

So for example:

Analytics:
Push Notifications: 5
Messages Dispatched: 3245
Messages Opened: 527
Average Open Rate: 18.5%

Sidebar Stats:
1 Variant
5 Notifications
680 Devices

**Comment by matzew** [comment]
@lfryc @sebastienblanc +1

**Comment by lfryc** [comment]
Hmm one more slight change in wording: conceptually we call `UnifiedPushMessage` something that is sent to the UPS, and UPS then dispatches "a message" to push networks, which is then opened as notification,

So correctly I would vote for:

Push Messages: 5
Notifications Opened: 527

and to be consistent: Notifications Dispatches: 3245

I will also leverage tooltips ? to describe in full detail.

**Comment by sebastienblanc** [comment]
+1 , `Notifications Dispatched` and not `Dispatches`

**Comment by lfryc** [comment]
yes, a small typo :-)

**Comment by lfryc** [comment]
Stats Wording with Tooltip

**Comment by matzew** [comment]
> +1 , Notifications Dispatched and not Dispatches

:+1:

On Thu, Jun 4, 2015 at 9:15 AM, Sebastien Blanc <notifications@github.com>
wrote:

> +1 , Notifications Dispatched and not Dispatches
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/580#issuecomment-108761877>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by sebastienblanc** [comment]
I like the screenshot ! +1

**Comment by lfryc** [comment]
ok, rebased, ready for final testing

**Comment by sebastienblanc** [comment]
:+1: merging

**Pull request merged**
