### PR TITLE
send badge payload only when needed, to avoid a hard reset

### PR DESCRIPTION
**Pull request by matzew**
https://issues.jboss.org/browse/AGPUSH-1495

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc @danbev mind to review ?

**Comment by lfryc** [comment]
@matzew I can't see any JIRA issue referenced, was just curious if this was reported or came up during a testing?

**Comment by sebastienblanc** [comment]
@lfryc it comes from a community request on the mailing list.

**Comment by danbev** [comment]
:eyes:

**Comment by danbev** [comment]
:+1: 
@matzew Looks good. As a suggestion, perhaps we can add a few [tests](https://github.com/matzew/aerogear-unifiedpush-server/pull/10) for this as well?

**Comment by danielpassos** [comment]
> @lfryc it comes from a community request on the mailing list.

Anyway let's create a JIRA to track it.

**Comment by sebastienblanc** [comment]
@danielpassos  Jira link has been added by @matzew

**Pull request merged**
