### PR TITLE
Change REST endpoints response type from "text/plain" to "application/json" with empty JSON body

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
See https://issues.jboss.org/browse/AGPUSH-1376

@lfryc I think that we may do the same for `/registry/device/importer/`. WDYT?

### CODE REVIEW

**Comment by lfryc** [comment]
@idelpivnitskiy Yes, that one should respond with JSON as well.

**Comment by lfryc** [comment]
I've tested this and works fine!

**Comment by matzew** [comment]
@idelpivnitskiy wana address this in _this_ PR or in a different one?

**Comment by idelpivnitskiy** [comment]
@matzew if it possible to rename JIRA issue I could do it here. If not, we may create a new ticket

**Comment by idelpivnitskiy** [comment]
I've created sub-task https://issues.jboss.org/browse/AGPUSH-1396
Should I send a new PR for this?

**Comment by matzew** [comment]
feel free to include in this PR - that's totally fine :-)

On Tue, May 5, 2015 at 2:56 AM, Idel Pivnitskiy <notifications@github.com>
wrote:

> I've created sub-task https://issues.jboss.org/browse/AGPUSH-1396
> Should I send a new PR for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/541#issuecomment-98895649>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by idelpivnitskiy** [comment]
@lfryc @matzew done :)

**Comment by lfryc** [comment]
:+1:

**Pull request merged**
