### PR TITLE
Pr473

### PR DESCRIPTION
**Pull request by kpiwko**

### CODE REVIEW

**Comment by sebastienblanc** [comment]
What is this PR ? Looks like a copy of https://github.com/aerogear/aerogear-unifiedpush-server/pull/473 ?

**Comment by kpiwko** [comment]
@sebastienblanc copy of #473 + reduced logging on Travis

**Comment by sebastienblanc** [comment]
@kpiwko Ah ok :) Maybe easier if you PR against @edewit existing PR no ? But it's the same in the end

**Comment by kpiwko** [comment]
Right, that would make more sense.

**Comment by matzew** [comment]
@kpiwko hrm -> https://s3.amazonaws.com/archive.travis-ci.org/jobs/50640435/log.txt

**Comment by matzew** [comment]
@kpiwko @edewit any updates?

**Comment by abstractj** [comment]
@kpiwko could you please update the description of this PR with what it was supposed to be + steps for testing?

I would appreciate.

**Comment by matzew** [comment]
@kpiwko closing...

**Comment by kpiwko** [comment]
@abstractj @matzew sorry, I had to unsubscribe myself from all Aerogear GH repositories to be able to track direct mentions.

I'll try to rebase the commit later this week and make travis happy on https://github.com/aerogear/aerogear-unifiedpush-server/pull/473

**Pull request closed without merging**
