### PR TITLE
Gcm topics

### PR DESCRIPTION
**Pull request by secondsun**
This is a migration of the PR from https://github.com/aerogear/aerogear-unifiedpush-server/pull/626

### CODE REVIEW

**Comment by matzew** [comment]
the gcm/ folder... should be just temporary - right?
IMO best is: we create a XMPP client lib (standalone) and use it as a dependency inside the UPS/GCM component

**Comment by secondsun** [comment]
@matzew I don't think the XMPP stuff is going to happen for a long time.  There is still a lot of work to be done on topics that I didn't expect (specifically how do we support alias and devicetype).

**Comment by matzew** [comment]
thats fine. But sounds reasonable to aim for 2.0 having XMPP?

the throughput via XMPP is also better, so worth to plan for it, in the
future ;-)

On Wednesday, August 12, 2015, Hoyt Summers Pittman <
notifications@github.com> wrote:

> @matzew <https://github.com/matzew> I don't think the XMPP stuff is going
> to happen for a long time. There is still a lot of work to be done on
> topics that I didn't expect (specifically how do we support alias and
> devicetype).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/630#issuecomment-130397506>
> .
>


-- 
Sent from Gmail Mobile

**Comment by secondsun** [comment]
@matzew I think 2.0 it is reasonable

**Comment by matzew** [comment]
there will be a newer PR for this work

**Comment by matzew** [comment]
Test run #1: https://github.com/aerogear/aerogear-unifiedpush-server/pull/708

**Pull request closed without merging**
