### PR TITLE
AGPUSH-1272: fix dashboard recent activity panel

### PR DESCRIPTION
**Pull request by sebastienblanc**
@lfryc @edewit : Could you review / merge ?

### CODE REVIEW

**Comment by edewit** [comment]
:+1:

**Comment by lfryc** [comment]
:eyes:

**Comment by lfryc** [comment]
:+1: merging

**Comment by lfryc** [comment]
Merged to master: https://github.com/aerogear/aerogear-unifiedpush-server/commit/a8530cfa4a496769a802dd8b3ebce42efc08450d

**Pull request closed without merging**
