### PR TITLE
making adm experimental

### PR DESCRIPTION
**Pull request by sebastienblanc**
@lfryc @matzew could you check&merge ?

### CODE REVIEW

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
Ok, I like the experimental, :+1: 

but, the variant code snippets are for Cordova.  

Since it's experimental... should we do something else ? 
e.g. point to the official Amazon doc ? and mention that the server is ready and and the SDK is in the works ?

**Comment by sebastienblanc** [comment]
Yeah, in the snippets , instead of code , we can point to doc, let me add this

**Comment by matzew** [comment]
@sebastienblanc wanna add something in this PR? Or should we close ?

**Comment by sebastienblanc** [comment]
No I will add something

**Comment by sebastienblanc** [comment]
@matzew PR has been updated

**Comment by matzew** [comment]
:eyeglasses:

**Comment by matzew** [comment]
@sebastienblanc I like that!

:+1: from my perspective!

**Comment by matzew** [comment]
merged to master

**Pull request closed without merging**
