### PR TITLE
Keycloak 120

### PR DESCRIPTION
**Pull request by matzew**
Adding Keycloak 1.2.0, done for [AGPUSH-1398](https://issues.jboss.org/browse/AGPUSH-1398) / [AGPUSH-1352](https://issues.jboss.org/browse/AGPUSH-1352)

Please test and review, @abstractj @cvasilak

### CODE REVIEW

**Comment by abstractj** [comment]
@matzew I have other things on my plate and I don't think it requires a security analysis, more testing. Feel free to ask others to review.

**Comment by matzew** [comment]
@secondsun mind to take a look ?

**Comment by matzew** [comment]
One thing I just noticed, clicking on the "account manager" link of our UPS console, I am redirected to the account manager, but on the SERVER console, I see:

```
08:55:49,958 ERROR [org.keycloak.freemarker.ExtendingThemeManager] (default task-20) Failed to find ACCOUNT theme patternfly, using built-in themes
08:55:49,987 ERROR [org.keycloak.freemarker.ExtendingThemeManager] (default task-28) Failed to find ACCOUNT theme patternfly, using built-in themes
```

@sebastienblanc @stianst any ideas?

**Comment by sebastienblanc** [comment]
@matzew maybe before looking further we should rebase so that we have the latest account styling changes from @andresgalante  ( https://github.com/aerogear/aerogear-unifiedpush-server/commit/08b34a3d8b8effe6d4e8b27a62aa9b7d011961eb )

**Comment by matzew** [comment]
well, it's rebased :-)

**Comment by matzew** [comment]
@sebastienblanc you mind to test ?

**Comment by sebastienblanc** [comment]
:+1:

**Pull request merged**
