### PR TITLE
Import export

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1393

Export and import :-)

How to test:

1. export
2. import

### CODE REVIEW

**Comment by sebastienblanc** [comment]
:eyes:

**Comment by sebastienblanc** [comment]
export works but I'm getting a problem with import 
```
TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at TypeError (native)
    at Scope.$scope.previewImport (http://localhost:8080/ag-push/scripts/scripts.3e5ba44a.js:1:14331)
    at fn (eval at <anonymous> (http://localhost:8080/ag-push/scripts/modules.ee3bbb30.js:13:11791), <anonymous>:2:230)
    at Scope.destination.(anonymous function) [as onChange] (http://localhost:8080/ag-push/scripts/modules.ee3bbb30.js:9:14896)
    at http://localhost:8080/ag-push/scripts/scripts.3e5ba44a.js:1:31215
    at Scope.$eval (http://localhost:8080/ag-push/scripts/modules.ee3bbb30.js:11:7362)
    at Scope.$apply (http://localhost:8080/ag-push/scripts/modules.ee3bbb30.js:11:7689)
    at HTMLInputElement.<anonymous> (http://localhost:8080/ag-push/scripts/scripts.3e5ba44a.js:1:31042)
    at HTMLInputElement.jQuery.event.dispatch (http://localhost:8080/ag-push/scripts/modules.ee3bbb30.js:3:15003)
    at HTMLInputElement.elemData.handle (http://localhost:8080/ag-push/scripts/modules.ee3bbb30.js:3:9833)
```

**Comment by sebastienblanc** [comment]
Using Chrome Version 43.0.2357.65 (64-bit)

Same issue with Firefox 33.1 but that is known issue

**Comment by lfryc** [comment]
Seems that it was issue with minification, @sebastienblanc it should work now.

Sorry, I should have tested it with `dist` version.

**Comment by sebastienblanc** [comment]
All good now :)
One remark : would it be possible to refresh the variant details after the import to directly show the devices imported ? It's a bit confusing now that it's still says "no registered devices" after the import popup has been closed.

**Comment by lfryc** [comment]
@sebastienblanc created issue and explained why I don't want to fix it now: https://issues.jboss.org/browse/AGPUSH-1443

**Comment by sebastienblanc** [comment]
make sense ,merging

**Pull request merged**
