### PR TITLE
Fixed .gitignore and maven-clean-plugin for admin-ui

### PR DESCRIPTION
**Pull request by idelpivnitskiy**

### CODE REVIEW

**Comment by lfryc** [comment]
Interesting, I don't have any `node_tmp` folder locally, can it be a leftover from an inconsistent state?

**Comment by idelpivnitskiy** [comment]
@lfryc yes, if you have an exception during `install node and npm` step, this folder won't be removed

**Comment by lfryc** [comment]
Nice catch @idelpivnitskiy

**Comment by lfryc** [comment]
:+1: tested locally, looks fine

**Comment by lfryc** [comment]
:rocket: Landed: https://github.com/aerogear/aerogear-unifiedpush-server/commit/d4fb0e0d6f61e8dc311ee1fe51c671d7e96f39a6

**Comment by idelpivnitskiy** [comment]
@lfryc thanks!)

**Pull request closed without merging**
