### PR TITLE
improve Send Notification dialog AGPUSH-1389

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1389

Testing:

* click 'Send Notification to this app'
 * verify that close button works
 * [interactive combo-box should be visible](http://andresgalante.com/ups-console/app-detail-variants.html) instead of standard `<select multiple />` combo box

### CODE REVIEW

**Comment by lfryc** [comment]
@andresgalante I did some small changes to LESS in order to avoid need for another icon set (glypicons) when the one we used already (font-awesome) can be used.

**Comment by lfryc** [comment]
unrelated test failure

**Comment by matzew** [comment]
:+1:

**Comment by sebastienblanc** [comment]
:+1:

**Pull request merged**
