### PR TITLE
Add check for rejected message

### PR DESCRIPTION
**Pull request by matzew**
Fixing NPE in APNs reject, as reported for [AGPUSH-1545](https://issues.jboss.org/browse/AGPUSH-1545)

### CODE REVIEW

**Comment by danielpassos** [comment]
:+1:

**Comment by lfryc** [comment]
@matzew how would you recommend testing this manually, against real device?

Also, should we have a unit test for this?

**Comment by matzew** [comment]
Its hard to actually test a APNs reject

On Wed, Dec 2, 2015 at 4:48 PM, Lukáš Fryč <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> how would you recommend testing this
> manually, against real device?
>
> Also, should we have a unit test for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/649#issuecomment-161340677>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by lfryc** [comment]
Should we unit test the case then?

**Comment by matzew** [comment]
ok, sure - let me add something

On Wed, Dec 2, 2015 at 5:49 PM, Lukáš Fryč <notifications@github.com> wrote:

> Should we unit test the case then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/649#issuecomment-161361354>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by lfryc** [comment]
Thinkins about it more, the unit testing is not worth here atm, given it is simple check and we will replace it with HTTP/2 soon. (as @matzew explained to me)

:+1: will merge

**Pull request merged**
