### PR TITLE
some cleanup

### PR DESCRIPTION
**Pull request by matzew**
@abstractj mind to review ?

### CODE REVIEW

**Comment by abstractj** [comment]
@matzew landed, let me know if your commit must go on 1.0.x

**Comment by abstractj** [comment]
Never mind, we don't have that branch anymore, 'doh

**Comment by matzew** [comment]
Right, the 1.0.x was deleted since we no longer develop on that 1.0.3 was the last release - also this did not work there, because we did not have enabled KC access token (but this is now the default of KC)

**Comment by abstractj** [comment]
@matzew as I said....never mind

**Pull request merged**
