### PR TITLE
Gcm canonical

### PR DESCRIPTION
**Pull request by matzew**
@sinarz I have squashed your commits to one, and did the same for me

### CODE REVIEW

**Comment by matzew** [comment]
@secondsun @sinarz mind taking a look? I did an update earlier, and cleaned up the commits

**Comment by matzew** [comment]
@sinarz @secondsun looks good ? Or any concerns on this PR ?

**Comment by secondsun** [comment]
+1

**Comment by viezel** [comment]
+1

**Comment by matzew** [comment]
@viezel @secondsun thanks, gentlemen! I'll merge it in a bit :mega:

**Comment by matzew** [comment]
landed in master: b19e913fd8ece8034a3cf96f96405f396e786dfd  & fbe006521dc317b2d46edda415b33ad4a6e1da14

and 1.1.x:  4af1b5345437dd74acfadf5945652dee65e441c4  &  a0813a6caf8a8ee585a1a5fe4b9c66bdfec8bbe3

**Comment by sinarz** [comment]
sry I was in vacation and couldn't login for few days. Thanks @matzew

**Pull request closed without merging**
