### PR TITLE
Removing iteration for unneeded token spit

### PR DESCRIPTION
**Pull request by matzew**
done for https://issues.jboss.org/browse/AGPUSH-1419
@lfryc clean up of unneeded code

### CODE REVIEW

**Comment by lfryc** [comment]
@matzew I guess we should enforce batches less than 1000 tokens in android configuration. Worth a JIRA probably

**Comment by edewit** [comment]
Instead of waiting for the list to be empty and removing the elements it could iterate over the chunks:
```java
        for (int i = 0; i < registrationIDs.size() / GCM_PAGE + 1; i++) {
            int chunkSize = Math.min(registrationIDs.size(), (i + 1) * GCM_PAGE);
            List<String> sublist = registrationIDs.subList(i  * GCM_PAGE, chunkSize);
        }
```

**Comment by matzew** [comment]
but we just send 1k tokenz to a GCMSender now. more does not make sense,
therefore the code remove

On Thursday, May 21, 2015, Erik Jan de Wit <notifications@github.com> wrote:

> Instead of waiting for the list to be empty and removing the elements it
> could iterate over the chunks:
>
>         for (int i = 0; i < registrationIDs.size() / GCM_PAGE + 1; i++) {
>             int chunkSize = Math.min(registrationIDs.size(), (i + 1) * GCM_PAGE);
>             List<String> sublist = registrationIDs.subList(i  * GCM_PAGE, chunkSize);
>         }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/566#issuecomment-104341637>
> .
>


-- 
Sent from Gmail Mobile

**Comment by delalis** [comment]
Hey guys, is this a specific fix that will address my concurrentModificationException?  

If so, when would you expect a build would be available for us to download?  

Thanks for addressing this so quickly.

fyi, here are the links I'm referring to:

https://issues.jboss.org/browse/AGPUSH-1419

http://aerogear-dev.1069024.n5.nabble.com/Android-GCM-PUSH-ERROR-Error-sending-payload-to-GCM-server-java-util-ConcurrentModificationException-td11655.html#a11664

**Comment by matzew** [comment]
@delalis we are releasing 1.1.0-beta.1 early nexxt week.

your fix is for -beta.2, a few weeks later

**Comment by edewit** [comment]
@matzew just out of curiosity where is this 1k token split now?

**Comment by matzew** [comment]
https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/push/sender/src/main/java/org/jboss/aerogear/unifiedpush/message/configuration/SenderConfigurationProvider.java#L46

On Fri, May 22, 2015 at 9:33 AM, Erik Jan de Wit <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> just out of curiosity where is this
> 1k token split now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/566#issuecomment-104549940>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by lfryc** [comment]
@edewit the configuration is than respected by the TokenLoader: https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/push/sender/src/main/java/org/jboss/aerogear/unifiedpush/message/TokenLoader.java#L117

**Comment by lfryc** [comment]
@matzew thinking about it a bit more, it still can be beneficial to do splitting to 1000 tokens in the sender itself:

say we want to optimize the flow, and we want to submit 5000 tokens in one batch for GCM sender, so that the sender will do 5 subsequent connections with 1000 devices within one transaction.

----

However in this state, if user reconfigures `-Daerogear.android.batchSize=1500`, the sender will fail, right?

**Comment by matzew** [comment]
a few comments:
* So we do some logic to dispatch 5k tokens, in one batch.
* we add somewhat similar logic to split that to 1k per sender.

Wouldn't it be nice to have the sender not worrying about that ? 

I think the `-Daerogear.android.batchSize=1500` is not a good config. it should be ignored, until we have the XMPP based stuff

**Comment by lfryc** [comment]
Okay, I'm fine with either of solutions, i will create an issue to cover
that.

**Comment by matzew** [comment]
@lfryc what would be the actual benefit if we keep the iteration inside of the sender?
Less of resources?

**Comment by sebastienblanc** [comment]
@matzew @lfryc are we in agreement for this PR ?

**Comment by matzew** [comment]
Not sure :-)

**Comment by lfryc** [comment]
If we keep sender splitting the GCM, we will make sure the impl is correct without being tied to the configuration of the component (TokenLoader) before.

Otherwise we need to make sure user won't be able to misconfigure (sanitize the case of configuration). We don't have any config validation ATM, but since we should also warn him he misconfigured in case of iOS batches or number of parallel iOS senders, we need to introduce this config validation anyway.

**Comment by lfryc** [comment]
I.e. if we keep this impl, we have to sanitize the user configuration in https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/push/sender/src/main/java/org/jboss/aerogear/unifiedpush/message/configuration/SenderConfigurationProvider.java#L46

**Comment by lfryc** [comment]
Okay, I will send a PR here to do required configuration validation changes.

**Comment by matzew** [comment]
@lfryc perfect!

**Comment by lfryc** [comment]
Here you go: https://github.com/matzew/aerogear-unifiedpush-server/pull/8

**Pull request merged**
