### PR TITLE
Enabling 1.6.1 version of the plugin

### PR DESCRIPTION
**Pull request by matzew**
@idelpivnitskiy @sebastienblanc mind to check

### CODE REVIEW

**Comment by sebastienblanc** [comment]
:+1: 

Regarding the warnings that Miredot gives us do we have a jira to track this ? 
miredot

**Comment by matzew** [comment]
sure, we can fix them as we move on - or feel free to send a PR

On Mon, Jun 15, 2015 at 9:34 AM, Sebastien Blanc <notifications@github.com>
wrote:

> [image: :+1:]
>
> Regarding the warnings that Miredot gives us do we have a jira to track
> this ?
> [image: miredot]
> <https://cloud.githubusercontent.com/assets/335133/8155155/9a505a5c-1341-11e5-84c0-62f038bdcd44.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/593#issuecomment-111967337>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by idelpivnitskiy** [comment]
:+1: 
I'll send additional PR with new features of 1.6.1 later, after some work on webpush

**Comment by matzew** [comment]
landed

**Pull request closed without merging**
