### PR TITLE
UI for Pending status of notification sending process AGPUSH-1441

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGPUSH-1441

Testing:

* create several variants, register some devices and then push
* first you can see just status Pending when table refreshes after push, but later it changes to Success/Failed
* this UI suffers from following issue though: https://issues.jboss.org/browse/AGPUSH-1445

### CODE REVIEW

**Comment by lfryc** [comment]
@sebastienblanc mind to test this? :football:

**Comment by matzew** [comment]
@lfryc 

running the tests:

```
Results :

Failed tests:
  TestMetricsCollector.test:106 expected:<2> but was:<0>

Tests run: 33, Failures: 1, Errors: 0, Skipped: 2
```

**Comment by matzew** [comment]
@lfryc Travis has same error

**Comment by lfryc** [comment]
Fixed and rebased on master @matzew

**Comment by matzew** [comment]
:+1: tested and works fine!

**Comment by sebastienblanc** [comment]
awesome stuff ! 
works here as well, tested with successful and failed, both start with pending.
merging

**Pull request merged**
