### PR TITLE
Adding angular.js resolution for Bower

### PR DESCRIPTION
**Pull request by kpiwko**

### CODE REVIEW

**Comment by sebastienblanc** [comment]
I'm pretty sure we had that before and then it was removed :) , I would like to have @lfryc opinion on that

**Comment by lholmquist** [comment]
i think i've noticed this also,  but when going from the 1.0.X branch to the master branch and vice versa.

I think i had to do a rm -rf on my bower_components directory

**Comment by lfryc** [comment]
@kpiwko have you tried to remove the `bower_components` and install it?

I know we are oscilating between including the `resolution` and removing it for quite some time. :-)

**Comment by matzew** [comment]
@lfryc 
> have you tried to remove the bower_components and install it?

why is that manual step needed ?

**Comment by sebastienblanc** [comment]
What is the status of this ? Do we know which way we want to go (including or removing `resolution`) ?

**Comment by lfryc** [comment]
If you are switching branches, you should do `frontend.clean.force` as documented here: https://github.com/aerogear/aerogear-unifiedpush-server/#cleaning-the-admin-ui-build

You should not experience this issue.

I'm :-1: , because I know we will remove it later eventually: https://github.com/aerogear/aerogear-unifiedpush-server/commit/74523afde6447149578e527ec2da627fbacf2142

**Comment by matzew** [comment]
ok, lets' close this

On Wed, Feb 25, 2015 at 12:57 PM, Lukáš Fryč <notifications@github.com>
wrote:

> If you are switching branches, you should do frontend.clean.force as
> documented here:
> https://github.com/aerogear/aerogear-unifiedpush-server/#cleaning-the-admin-ui-build
>
> You should not experience this issue.
>
> I'm [image: :-1:] , because I know we will remove it later eventually:
> 74523af
> <https://github.com/aerogear/aerogear-unifiedpush-server/commit/74523afde6447149578e527ec2da627fbacf2142>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-server/pull/492#issuecomment-75948516>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by lfryc** [comment]
Thanks @kpiwko , let me know if you will reproduce the issues and `frontend.clean.force` won't help you to fix that.

**Pull request closed without merging**
