### PR TITLE
wording changes following patternfly recomendations

### PR DESCRIPTION
**Pull request by andresgalante**
@sebastienblanc @lfryc @matzew 
I've change some words to follow [Patternfly terminology and wording](https://www.patternfly.org/styles/terminology-and-wording/) recommendations

If you want keep the PR open, I'll send changes to the login screen soon.

### CODE REVIEW

**Comment by lfryc** [comment]
Okay, let's send the screen, I like the alignments you already sent.

**Comment by sebastienblanc** [comment]
sounds good, go go go for the screens

**Comment by andresgalante** [comment]
@sebastienblanc @lfryc @matzew 
This login screen is placeholder. The final goal (for final) is to change the html to follow patternfly structure:
http://andresgalante.com/ups-console/login.html

**Comment by matzew** [comment]
Thanks, landed!

**Pull request closed without merging**
