### PR TITLE
add migrator to dist bundle

### PR DESCRIPTION
**Pull request by sebastienblanc**
@secondsun Could you review ;) ?

### CODE REVIEW

**Comment by secondsun** [comment]
@sebastienblanc Would you mind pulling https://github.com/aerogear/aerogear-unifiedpush-server/pull/624 in as well?  Two birds, one stone for me ;)

**Comment by sebastienblanc** [comment]
@secondsun I cherry-picked it !

**Comment by secondsun** [comment]
@sebastienblanc WDYT making the names in the archive follow the format of finalName?

**Comment by sebastienblanc** [comment]
@secondsun you mean the name of the dist zip/tar ?

**Comment by secondsun** [comment]
@sebastienblanc Actually I found a better workaround than using a final name param for my usage.  I just get maven to give me the project version and I can do everythign I need with that

**Comment by secondsun** [comment]
+1

**Comment by sebastienblanc** [comment]
landed in f9b1be84e14c6d71100ba0d2bd6b5637829828be

**Pull request closed without merging**
