### PR TITLE
add tests for installations removal with categories

### PR DESCRIPTION
**Pull request by sebastienblanc**

### CODE REVIEW

**Comment by matzew** [comment]
@TadeasKriz @sebastienblanc before the change to orm.xml (related to this), shouldn't `findAndDeleteOneInstallation()` fail ?

**Comment by matzew** [comment]
@sebastienblanc @TadeasKriz any commets?

**Comment by sebastienblanc** [comment]
@matzew These are just additional tests to enlarge the test coverage, can not hurt to be merged IMO

**Comment by matzew** [comment]
@sebastienblanc what's the relationship to https://issues.jboss.org/browse/AGPUSH-1299 ?

**Comment by sebastienblanc** [comment]
Let me cherry-pick these tests on Master and "normally" it should fail

**Comment by matzew** [comment]
> Let me cherry-pick these tests on Master and "normally" it should fail

Ok, but since this is for 1.0.x, I'd say -> let's ship it, @sebastienblanc

**Pull request merged**
