### PR TITLE
UX revamp: last changes

### PR DESCRIPTION
**Pull request by lfryc**
The PR contains these fixes:

* https://issues.jboss.org/browse/AGPUSH-1344
* implemented dropdowns (user logout / account management)
* warnings when push message fails (self-updating)

To be merged to `ux-revamp` branch

### CODE REVIEW

**Comment by lfryc** [comment]
@danielpassos :chocolate_bar: is coming...

**Comment by danielpassos** [comment]
:eyes:

**Comment by danielpassos** [comment]
:heavy_check_mark: implemented dropdowns (user logout / account management)

screenshot 2015-04-22 16 30 38

:heavy_check_mark: warnings when push message fails (self-updating)

* I've received a message saying it was send, but the screen not refresh automatic

screenshot 2015-04-22 16 41 45

* After I refresh I can see the status _Failed_

screenshot 2015-04-22 16 43 35

**Comment by danielpassos** [comment]
:+1:

**Comment by lfryc** [comment]
Thanks for testing @danielpassos ,

the fact that it does not auto-update activity-log is caused by a fact that the sender REST endpoint is asynchronous -

the send request responds before a new push message information (activity log item) is written to the database.

That was changed in new JMS stuff in master, so it is going to resolve this.

**Comment by lfryc** [comment]
@danielpassos :chocolate_bar: :chocolate_bar: :chocolate_bar:

**Pull request merged**
